let data = [
    {
        id: "product_key_001",
        category:"women",
        name:"Esprit Ruffle Shirt",
        img:"/shopImage/product-01.jpg",
        price:65.25,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. equat ornare feugiat.",
    },
    {
        id: "product_key_002",
        category:"women",
        name:"Herschel supply",
        img:"/shopImage/product-02.jpg",
        price:45.25,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula.  consequat ornare feugiat.",
    },
    {
        id: "product_key_003",
        category:"men",
        name:"Only Check Trouser",
        img:"/shopImage/product-03.jpg",
        price:89.50,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae gula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_004",
        category:"women",
        name:"Classic Trench Coat",
        img:"/shopImage/product-04.jpg",
        price:58.79,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula.  ornare feugiat.",
    },
    {
        id: "product_key_005",
        category:"women",
        name:"Front Pocket Jumper",
        img:"/shopImage/product-05.jpg",
        price:68.00,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vigula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_006",
        category:"watch",
        name:"Vintage Inspired Classic",
        img:"/shopImage/product-06.jpg",
        price:45.25,
        title:"Nullar eget sem vitae eros pharetra itae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_007",
        category:"women",
        name:"Shirt in Stretch Cotton",
        img:"/shopImage/product-07.jpg",
        price:150.65,
        title:"Nullar eget sem vitae eros pharetra viverra. Namligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_008",
        category:"women",
        name:"Pieces Metallic Printed",
        img:"/shopImage/product-08.jpg",
        price:100.35,
        title:"Nullar eget sem vitae eros pharetra viverraluctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_009",
        category:"shoes",
        name:"Converse All Star Hi Plimsolls",
        img:"/shopImage/product-09.jpg",
        price:79.55,
        title:"Nullar eget sem vitae eros pharetra vww vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_010",
        category:"women",
        name:"Femme T-Shirt In Stripe",
        img:"/shopImage/product-10.jpg",
        price:42.65,
        title:"Nullar eget sem vitae eros pharetra Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_011",
        category:"men",
        name:"Herschel Moonlight",
        img:"/shopImage/product-11.jpg",
        price:84.25,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris rnare feugiat.",
    },
    {
        id: "product_key_012",
        category:"watch",
        name:"Herschel SpunBer",
        img:"/shopImage/product-12.jpg",
        price:89.00,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_013",
        category:"women",
        name:"T-Shirt with Sleeve",
        img:"/shopImage/product-13.jpg",
        price:99.00,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus  consequat ornare feugiat.",
    },
    {
        id: "product_key_014",
        category:"women",
        name:"Pretty Little Thing",
        img:"/shopImage/product-14.jpg",
        price:45.00,
        title:"Nullar eget sem vitae eros pharetra vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_015",
        category:"watch",
        name:"Mini Silver Mesh Watch",
        img:"/shopImage/product-15.jpg",
        price:59.25,
        title:"Nullar eget sem vitae eros pharetra  Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_016",
        category:"women",
        name:"Square Neck Back",
        img:"/shopImage/product-16.jpg",
        price:87.65,
        title:"Nullar eget sem vitae ero viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_017",
        category:"men",
        name:"ASC modern Theme Pocket",
        img:"/shopImage/product-17.jpg",
        price:45.85,
        title:"Nullar eget sem vitae eros pharetra viverra. tae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_018",
        category:"men",
        name:"	Lightweight Jacket",
        img:"/shopImage/product-18.jpg",
        price:77.75,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_019",
        category:"men",
        name:"	Fresh DarkThane",
        img:"/shopImage/product-19.jpg",
        price:180.35,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris cons feugiat.",
    },
    {
        id: "product_key_020",
        category:"men",
        name:"DNK Black shallots shirt",
        img:"/shopImage/product-20.jpg",
        price:399.5,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligul aequat ornare feugiat.",
    },
    {
        id: "product_key_021",
        category:"men",
        name:"DNK white samosas Shoes",
        img:"/shopImage/product-21.jpg",
        price:55.25,
        title:"Nullar eget sem vitae eros  viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_022",
        category:"men",
        name:"black dracula shirt",
        img:"/shopImage/product-22.jpg",
        price:69.00,
        title:"Nullar eget sem vitae eros pharetra viverra. luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_023",
        category:"watch",
        name:"overtime watch",
        img:"/shopImage/product-23.jpg",
        price:145.35,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_024",
        category:"bag",
        name:"supply longline bag",
        img:"/shopImage/product-24.jpg",
        price:88.00,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_025",
        category:"bag",
        name:"gray roadblock bag",
        img:"/shopImage/product-25.jpg",
        price:74.99,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
]


// console.log(data)